### ISSUE TITLE
Fuzzy Explaination about Retrieval Database

### ISSUE THREAD

**Issue by 1311894932** [mingyuan-zhang/ReMoDiffuse#13]
Hello Dr.Zhang! Thanks for sharing your work!!  However, there is a question which refused me for several days.
In the end of the chapter "Network Architecture" of paper, it says "As for the text encoder, the feature R^t from the last token is supposed to represent the global semantic information."
And in the code: 
class RetrievalDatabase:
        ...
        data = np.load(retrieval_file)
        self.clip_seq_features = data['clip_seq_features']

I mean, how do you get R^t? it seems like you just load them...and i dont understand the explaination in paper
Any response will be appreciated !!!

**Comment by mingyuan-zhang** [comment]
Sorry for the late reply. There are two steps to get $R^t$: 1) use frozen CLIP text encoder to convert the text prompt into a feature sequence; 2) use two learnable tranformer encoder layers to further process this sequence.

`data['clip_seq_features']` is the pre-calculated CLIP feature sequences for speeding up training and testing.

**Comment by 1311894932** [comment]
> Sorry for the late reply. There are two steps to get Rt: 1) use frozen CLIP text encoder to convert the text prompt into a feature sequence; 2) use two learnable tranformer encoder layers to further process this sequence.
> 
> `data['clip_seq_features']` is the pre-calculated CLIP feature sequences for speeding up training and testing.

Thanks a lot !!!!
