### ISSUE TITLE
Unnoticed modified std.npy of HumanML3D 

### ISSUE THREAD

**Issue by 1311894932** [mingyuan-zhang/ReMoDiffuse#15]
Hello Dr.Zhang! Sorry to bother you again...may i ask:

i just notice , it seems that there is a little difference in std between the dataset HumanML3D for training ReMoDiffuse : 
![image](https://github.com/mingyuan-zhang/ReMoDiffuse/assets/126459703/65d8082f-c288-411c-a86b-005baf83f559)

and the real HumanML3D : 
![image](https://github.com/mingyuan-zhang/ReMoDiffuse/assets/126459703/a2fde504-853c-4106-ae2c-399a0d148352)

 it looks like you have emphasized root's loss? I'm not sure...because "the real HumanML3D" i mentioned is made by myself (humanml3d let us process their raw data)

And I have trained ReMo using std of "the real HumanML3D",  loss from about 1.3 to 0.3 but the root in "test.gif" seems weird, and i use yours std.npy, loss from about 17 to 0.3,  every joint seems good!

Any response will be appreciated!!! and sorry again

**Comment by mingyuan-zhang** [comment]
Hi, this design follows the official implementation.

The official code of HumanML3D will re-compute the std in this line: https://github.com/EricGuo5513/text-to-motion/blob/750f6391bbdbc8bcc6a246d2583f1e6c412d5a25/data/dataset.py#L526

`opt.feat_bias` is set to 5 in this line: https://github.com/EricGuo5513/text-to-motion/blob/750f6391bbdbc8bcc6a246d2583f1e6c412d5a25/options/train_options.py#L55

However, if you train you model with the official implemantation, you will the find the re-compute std in the `meta` directory. The root std is actually divided by 25 (it seems that the division process has taken place 2 times).

In addition, just like you said, trajectory generation usually is more important than other joints. Foot sliding, overall jitter all result from the inaccurate trajectory.

**Comment by 1311894932** [comment]
omg, thanks so much!!!  please give me some time to take a look...

**Comment by 1311894932** [comment]
perhaps the FID in paper needs the model trained by large batchsize, in https://github.com/mingyuan-zhang/ReMoDiffuse/issues/5 , this bro failed at first,  then solved it by using batchsize 1024 , and i failed when my batchsize is 64 using one 3080.

**Comment by 1311894932** [comment]
> Hi, this design follows the official implementation.
> 
> The official code of HumanML3D will re-compute the std in this line: https://github.com/EricGuo5513/text-to-motion/blob/750f6391bbdbc8bcc6a246d2583f1e6c412d5a25/data/dataset.py#L526
> 
> `opt.feat_bias` is set to 5 in this line: https://github.com/EricGuo5513/text-to-motion/blob/750f6391bbdbc8bcc6a246d2583f1e6c412d5a25/options/train_options.py#L55
> 
> However, if you train you model with the official implemantation, you will the find the re-compute std in the `meta` directory. The root std is actually divided by 25 (it seems that the division process has taken place 2 times).
> 
> In addition, just like you said, trajectory generation usually is more important than other joints. Foot sliding, overall jitter all result from the inaccurate trajectory.

Excuse me, may i ask the initial error of motiondiffuse on your computer? mine is about 1.0, and the strangest thing is when I changed the std.npy, the error just change a little...which in remodiffuse the initial error is about 17(std.npy) or 1.3(Std.npy) 
Looking forward to hearing from you !!!
