### ISSUE TITLE
Hard to download data.zip from google drive

### ISSUE THREAD

**Issue by neptune4year** [mingyuan-zhang/ReMoDiffuse#2]
Dear authors,

Really appreciate your great job, we want to have a try to see the quality of generation of the motion. But the data.zip on google drive is too big and hard to download, it takes a very long time but easily lost the connection. May I ask you to put it somewhere else?

Thanks very much!

**Comment by mingyuan-zhang** [comment]
Hi, thanks for your interest in our work. May I know where you prefer to upload it?

**Comment by neptune4year** [comment]
> Hi, thanks for your interest in our work. May I know where you prefer to upload it?

First, we use a proxy and download it already.
Secondly, we prefer Baidu Netdist, we download from Baidu is much easier.

Thanks very much!

**Comment by mingyuan-zhang** [comment]
> > Hi, thanks for your interest in our work. May I know where you prefer to upload it?
> 
> First, we use a proxy and download it already. Secondly, we prefer Baidu Netdist, we download from Baidu is much easier.
> 
> Thanks very much!

Thanks for your advice. We have added a new download link from Baidu Netdisk.

Feel free to ask me if you have any further question~
